TeamDivers/Soar

- server/src/test/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryResponseDtoTest.java
- 이름이 변경된 DTO에 대해 기존 테스트 케이스 수정
- StudyHistoryResponseDtoTest 수정 (`StudyHistoryMetaResponseDto` -> `StudyHistoryOverviewDto`
- 테스트 로직은 동일합니다!
> 테스크 코드에 변경된 DTO 클래스 적용

- server/src/main/resources/data.sql
- server/src/test/java/com/konkuk/soar/SoarApplicationTests.java
- server/src/test/java/com/konkuk/soar/TestEntityFactory.java
- server/src/test/java/com/konkuk/soar/portfolio/dto/project/response/ProjectResponseDtoTest.java
- server/src/test/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryResponseDtoTest.java
- Member 도메인 변경에 따른 테스트 코드 변경
- Linux Mysql 정책에 따른 data.sql 변경
- 테스트 컨텍스트 수정
- `TestEntityFactory.member` 에 `email` 필드 추가
- `data.sql` 테이블 lower_case로 변경
- 테스트 컨텍스트에서 실제 운영에 사용되는 DB와 동일한 환경에서 테스트 하기 위해서 embedded h2 db 를 삭제하였습니다
- 테스트 엔티티 member 생성 로직 변경(필드 추가)
- yml 파일 변경 (application.yml, application-dev.yml, application-test.yml)
- yml 파일 삭제 (application-create.yml)
> 도메인 변경에 따른 오류와 배포 관련 DDL 변경

- server/src/main/java/com/konkuk/soar/common/dto/BaseResponse.java
- server/src/main/java/com/konkuk/soar/common/dto/BaseResponseStatus.java
- server/src/main/java/com/konkuk/soar/global/exception/ExceptionResult.java
- server/src/main/java/com/konkuk/soar/global/exception/NotFoundException.java
- server/src/main/java/com/konkuk/soar/global/exception/handler/GlobalExceptionHandler.java
- server/src/main/java/com/konkuk/soar/portfolio/service/SimplePortfolioService.java
- #26 
- 컨트롤러 예외처리에 필요한 예외처리 로직 구현
- `GlobalExceptionHandler` 등록
- `ExceptionResult` 클래스로 공통 응답 포맷 등록
> 컨트롤러 공통 ExceptionHandler 구현

- server/src/main/java/com/konkuk/soar/common/config/oauth/OAuth2SuccessHandler.java
- 로그인시 기존 요청에 token만 전달해줌
- 리다이렉트가 필요
- 요청 성공시 redirect되게 변경
> 로그인 성공시 리다이렉트되게 변경

- server/src/main/java/com/konkuk/soar/common/config/oauth/OAuth2SuccessHandler.java
- 리다이렉트 주소가 서버주소로 되던 문제
- referer를 보고 리다이렉트 되게 변경
> redirect주소 referer로 변경

- client/src/assets/images/crown.svg
- client/src/assets/images/index.ts
- client/src/assets/images/search.svg
- client/src/assets/styles/index.css
- client/src/components/Chip/index.tsx
- client/src/components/ChipList/index.tsx
- client/src/components/Ring/index.tsx
- client/src/components/layout/index.tsx
- client/src/routes/index.tsx
- client/src/routes/login/index.tsx
- client/src/routes/login/kakao.tsx
- client/src/routes/portfolio/index.tsx
- client/src/routes/ranking/index.tsx
- client/src/utils/color.ts
> Ranking page imple(1/2)

- server/src/main/java/com/konkuk/soar/common/dto/BaseResponse.java
- server/src/main/java/com/konkuk/soar/common/dto/file/request/FileCreateDto.java
- server/src/main/java/com/konkuk/soar/common/dto/file/response/FileResponseDto.java
- server/src/main/java/com/konkuk/soar/common/dto/tag/request/TagCreateDto.java
- server/src/main/java/com/konkuk/soar/common/dto/tag/response/TagListResponseDto.java
- server/src/main/java/com/konkuk/soar/member/controller/MemberController.java
- server/src/main/java/com/konkuk/soar/member/dto/request/MemberCreateDto.java
- server/src/main/java/com/konkuk/soar/member/dto/request/MemberUpdateRequestDto.java
- server/src/main/java/com/konkuk/soar/member/dto/response/MemberResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/controller/PortfolioController.java
- server/src/main/java/com/konkuk/soar/portfolio/controller/ProjectController.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioCreateLargeDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioReviewResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/request/ProjectCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/response/ProjectOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/response/ProjectResponseDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/controller/StudyHistoryController.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/request/StudyHistoryCreateDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryCalendarDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryOverviewDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryResponseDto.java
- #43 
- controller, dto에 swagger 설정
> controller, dto swagger 설정

- server/src/main/java/com/konkuk/soar/common/dto/BaseResponse.java
- server/src/main/java/com/konkuk/soar/common/dto/file/request/FileCreateDto.java
- server/src/main/java/com/konkuk/soar/common/dto/file/response/FileResponseDto.java
- server/src/main/java/com/konkuk/soar/common/dto/tag/request/TagCreateDto.java
- server/src/main/java/com/konkuk/soar/common/dto/tag/response/TagListResponseDto.java
- server/src/main/java/com/konkuk/soar/member/controller/MemberController.java
- server/src/main/java/com/konkuk/soar/member/dto/request/MemberCreateDto.java
- server/src/main/java/com/konkuk/soar/member/dto/request/MemberUpdateRequestDto.java
- server/src/main/java/com/konkuk/soar/member/dto/response/MemberResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/controller/PortfolioController.java
- server/src/main/java/com/konkuk/soar/portfolio/controller/ProjectController.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioCreateLargeDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioReviewResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/request/ProjectCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/response/ProjectOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/response/ProjectResponseDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/controller/StudyHistoryController.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/request/StudyHistoryCreateDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryCalendarDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryOverviewDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryResponseDto.java
- #43 
- controller, dto에 swagger 설정
> feat: controller, dto에 swagger 설정

- server/src/main/java/com/konkuk/soar/portfolio/controller/PortfolioController.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/PortfolioScore.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/repository/PortfolioReviewRepository.java
- server/src/main/java/com/konkuk/soar/portfolio/service/PortfolioService.java
- server/src/main/java/com/konkuk/soar/portfolio/service/SimplePortfolioService.java
- #41 
- 포트폴리오 랭킹 로직 구현
- PortfolioService에 랭크를 구하는 함수 추가
- PortfolioOverview, PortfolioResponseDto 에 `score`, `rank` 필드 추가
다음과 같이 응답하도록 처리하였습니다
> 포트폴리오 랭킹 로직 구현

- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioResponseDto.java
- docs: swagger description 수정
- 포트폴리오 dto description 수정
> docs: swagger description 수정

- server/build.gradle
- server/src/main/java/com/konkuk/soar/common/config/S3Config.java
- server/src/main/java/com/konkuk/soar/common/controller/AwsController.java
- server/src/main/java/com/konkuk/soar/common/dto/file/request/FileCreateDto.java
- server/src/main/java/com/konkuk/soar/common/service/AwsS3Service.java
- server/src/main/java/com/konkuk/soar/common/service/FileService.java
- server/src/main/java/com/konkuk/soar/common/service/SimpleFileService.java
- #36 
- s3 config 추가
- file service 추가
- application.yaml에 aws 관련 설정 추가
> S3 파일업로드 구현

- client/src/apis/record/createRecord.ts
- client/src/components/RoundButton/index.tsx
- client/src/routes/login/index.tsx
- client/src/routes/login/kakao.tsx
- client/src/routes/login/onboard.tsx
- client/src/routes/login/signup.tsx
- client/tsconfig.paths.json
> [client] Breaking Changes

- server/src/main/java/com/konkuk/soar/common/service/FileService.java
- server/src/main/java/com/konkuk/soar/common/service/SimpleFileService.java
- server/src/main/java/com/konkuk/soar/global/exception/NotFoundException.java
- server/src/main/java/com/konkuk/soar/portfolio/controller/ProjectController.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/request/ProjectCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/service/ProjectService.java
- server/src/main/java/com/konkuk/soar/portfolio/service/SimpleProjectService.java
- server/src/main/java/com/konkuk/soar/studyhistory/controller/StudyHistoryController.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/request/StudyHistoryCreateDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/service/SimpleStudyHistoryService.java
- server/src/main/java/com/konkuk/soar/studyhistory/service/StudyHistoryService.java
- #64 
- 프로젝트, 학습기록 생성할 때 파일 업로드 기능 구현
- 프로젝트 생성 시 파일 업로드 구현
- 학습기록 생성 시 파일 업로드 구현
- FileService 추가 메소드 있습니다
> 프로젝트, 학습기록 생성할 때 파일 업로드 기능 구현

- server/src/main/java/com/konkuk/soar/common/config/oauth/OAuth2SuccessHandler.java
- #59 
- URI에 토큰 같이 전달되게 변경
- security 이상해요
- oauth2 성공시 `redirect?code=TOKEN`
> RedirectURI에 토큰 전달

- server/src/main/java/com/konkuk/soar/member/controller/MemberController.java
- server/src/main/java/com/konkuk/soar/member/domain/Member.java
- server/src/main/java/com/konkuk/soar/member/dto/response/MemberResponseDto.java
- server/src/main/java/com/konkuk/soar/member/service/MemberService.java
- server/src/main/java/com/konkuk/soar/member/service/SimpleMemberService.java
- #66 
- 멤버에 thumbnail 추가
- `api/members/thumbnail` 썸네일 변경 api 추가
> Member에 thumbnail 추가

- server/src/main/java/com/konkuk/soar/studyhistory/controller/StudyHistoryController.java
- server/src/main/java/com/konkuk/soar/studyhistory/repository/StudyHistoryRepository.java
- server/src/main/java/com/konkuk/soar/studyhistory/service/SimpleStudyHistoryService.java
- server/src/main/java/com/konkuk/soar/studyhistory/service/StudyHistoryService.java
- server/src/main/resources/data.sql
- #71 
- 학습 기록 controller에 있는 size 파라미터 제거
- 학습 기록 controller만 제거. 포트폴리오 controller는 따로 해야됨.
> size -> findAll로 수정 (#71)

- server/src/main/java/com/konkuk/soar/common/controller/AwsController.java
- server/src/main/java/com/konkuk/soar/member/controller/MemberController.java
- server/src/main/java/com/konkuk/soar/portfolio/controller/PortfolioController.java
- server/src/main/java/com/konkuk/soar/portfolio/controller/ProjectController.java
- server/src/main/java/com/konkuk/soar/studyhistory/controller/StudyHistoryController.java
- server/src/main/resources/data.sql
- #79
- controller에 cors 추가
- DDL 변경
> feat: cors 해결 (#79)

- server/src/main/java/com/konkuk/soar/common/dto/BaseResponse.java
- server/src/main/java/com/konkuk/soar/common/dto/file/response/FileResponseDto.java
- server/src/main/java/com/konkuk/soar/common/dto/tag/request/TagCreateDto.java
- server/src/main/java/com/konkuk/soar/common/dto/tag/response/TagListResponseDto.java
- server/src/main/java/com/konkuk/soar/member/dto/request/MemberUpdateRequestDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioCreateLargeDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioReviewResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/request/ProjectCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/response/ProjectOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/response/ProjectResponseDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/request/StudyHistoryCreateDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryCalendarDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryOverviewDto.java
- server/src/main/java/com/konkuk/soar/studyhistory/dto/response/StudyHistoryResponseDto.java
- server/src/main/resources/data.sql
> Swagger 최신화

- server/src/main/java/com/konkuk/soar/portfolio/domain/portfolio/Portfolio.java
- server/src/main/java/com/konkuk/soar/portfolio/domain/project/Project.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/project/request/ProjectCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/service/SimplePortfolioService.java
- server/src/main/java/com/konkuk/soar/portfolio/service/SimpleProjectService.java
- server/src/main/resources/data.sql
> background 필드 Project -> Portfolio로 변경 (#84)

- server/src/main/java/com/konkuk/soar/portfolio/controller/PortfolioController.java
- server/src/main/java/com/konkuk/soar/portfolio/domain/portfolio/PortfolioReview.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/request/PortfolioReviewCreateDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioOverviewDto.java
- server/src/main/java/com/konkuk/soar/portfolio/dto/portfolio/response/PortfolioResponseDto.java
- server/src/main/java/com/konkuk/soar/portfolio/service/PortfolioService.java
- server/src/main/java/com/konkuk/soar/portfolio/service/SimplePortfolioService.java
- 포트폴리오 평가 API 구현
- 포트폴리오 평가 API 구현
> 포트폴리오 평가 API 구현
